# Generated by Django 3.1.2 on 2020-10-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_image_location1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='location1',
            new_name='category1',
        ),
    ]
