# Generated by Django 3.1.2 on 2020-10-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20201010_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
    ]
