# Generated by Django 2.2 on 2020-10-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20201012_1242'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
